# -*- coding: utf-8 -*-
"""CASE STUDY 2 - BAR CHART AND HEATMAP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G_syzy_yADG4URBbpmZAaK7U8fWwaPR8
"""

#pivot and top 10

import pandas as pd
from typing import Dict, Any

class CustomAnalyzer:

  def get_pivot(self, df: pd.DataFrame) -> pd.DataFrame:
    cat_first = self.config["category_first"]
    cat_second = self.config["category_second"]
    measure = self.config["measure_column"]

    work = df.copy()
    work[cat_first] = work[cat_first].fillna("MISSING")
    work[cat_second] = work[cat_second].fillna("MISSING")

    pivot_table = pd.pivot_table(
        work,
        values=measure,
        index=[cat_first, cat_second],
        aggfunc="sum",
        margins=True,
        margins_name="Total",
        dropna=False
    )

    return pivot_table

    def get_top10(self, grouped_df: pd.DataFrame) -> pd.DataFrame:
      sum_col = f"{self.config['measure_column']}_sum"

      top10 = grouped_df.sort_values(by=sum_col, ascending=False).head(10)

      return top10

def get_pivot(self, df: pd.DataFrame) -> pd.DataFrame:
        cat_first = self.config["category_first"]
        cat_second = self.config["category_second"]
        measure = self.config["measure_column"]

        work = df.copy()
        work[cat_first] = work[cat_first].fillna("MISSING")
        work[cat_second] = work[cat_second].fillna("MISSING")

        pivot_table = pd.pivot_table(
            work,
            values=measure,
            index=cat_first,
            columns=cat_second,
            aggfunc="sum",
            margins=True,
            margins_name="Total",
            dropna=False
        )

        return pivot_table

    def get_top10(self, grouped_df: pd.DataFrame) -> pd.DataFrame:
        sum_col = f"{self.config['measure_column']}_sum"

        top10 = grouped_df.sort_values(by=sum_col, ascending=False).head(10)

        return top10

import matplotlib.pyplot as plt
import seaborn as sns

analyzer = CustomAnalyzer(config)

#bar chart of top 10
top10 = analyzer.get_top10(analyzer.get_grouped(df))
sum_col = f"{config['measure_column']}_sum"
labels = top10[config["category_first"]].astype(str) + " / " + top10[config["category_second"]].astype(str)

plt.figure(figsize=(10, 6))
plt.bar(labels, top10[sum_col])
plt.xticks(rotation=45, ha="right")
plt.ylabel(sum_col)
plt.title("Top 10")
plt.tight_layout()
plt.savefig("bar.png", dpi=150)
plt.show()

#heat map of pivot excluding margins
pivot = analyzer.get_pivot(df)
pivot_no_margins = pivot.drop(index="Total", errors="ignore").drop(columns="Total", errors="ignore")

plt.figure(figsize=(10, 8))
sns.heatmap(pivot_no_margins, annot=True, fmt=".0f", cmap="viridis")
plt.title("Pivot Heatmap (excluding margins)")
plt.tight_layout()
plt.savefig("heatmap.png", dpi=150)
plt.show()